# tasks file for deploy_monitoring_logging
- name: Deploy Monitoring and Logging Tools
  hosts: kube_monitoring
  gather_facts: False
  tasks:
  - name: Install Helm Diff plugin
    shell: "helm plugin install https://github.com/databus23/helm-diff || true"
    args:
      executable: /bin/bash

  - name: Add Prometheus Helm repository
    shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

  - name: Add Grafana Helm repository
    shell: helm repo add grafana https://grafana.github.io/helm-charts

  - name: Install Prometheus Helm chart
    kubernetes.core.helm:
      name: prometheus
      chart_ref: prometheus-community/kube-prometheus-stack
      release_namespace: monitoring
      create_namespace: true
      wait_timeout: 600
      release_values:
        prometheus:
          prometheusSpec:
            retention: '7d'
        grafana:
          enabled: false
    register: helm_install
    until: helm_install is succeeded
    retries: 5
    delay: 10

  - name: Install Grafana Loki Helm chart
    kubernetes.core.helm:
      name: loki
      chart_ref: grafana/loki-stack
      release_namespace: logging
      create_namespace: true
      release_values:
        promtail:
          enabled: true

  - name: Install Grafana Helm chart
    kubernetes.core.helm:
      name: grafana
      chart_ref: grafana/grafana
      release_namespace: monitoring
      release_values:
        adminPassword: "{{ grafana_password }}"
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server.monitoring.svc.cluster.local
              access: proxy
              isDefault: true
            - name: Loki
              type: loki
              url: http://loki.logging.svc.cluster.local
              access: proxy
