
- name: Get kubeconfig from master node
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: "/tmp/admin.conf"
    flat: yes
  become: yes
  delegate_to: kube-master1

- name: Ensure .kube directory exists
  file:
    path: "/root/.kube"
    state: directory
  become: yes

- name: Copy kubeconfig to worker nodes
  copy:
    src: "/tmp/admin.conf"
    dest: "/root/.kube/config"
  become: yes

- name: Check if kubeconfig exists on worker nodes
  stat:
    path: "/root/.kube/config"
  become: yes
  register: kubeconfig_stat

- debug:
    msg: "/root/.kube/config exists on the worker node."
  when: kubeconfig_stat.stat.exists

- name: Ensure .kube directory exists in /home/{{ ansible_user }}
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  become: yes

- name: Copy kube config to /home/{{ ansible_user }}/.kube
  command:
    cmd: cp "/root/.kube/config" "/home/{{ ansible_user }}/.kube/config"
  become: yes

- name: Change file ownership and permissions
  file:
    path: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: yes
