# tasks file for mongodb_server_setup
- hosts: kube_db
  become: yes
  vars_files:
  - group_vars.yml

  tasks:
  - name: Update and Upgrade the system's packages
    apt:
      update_cache: yes
      upgrade: 'yes'

  - name: Install necessary packages
    apt:
      name:
      - libssl1.1
      - python3-pip
      state: present

  - name: Install pymongo
    pip:
      name: pymongo
      state: present

  - name: Import the public key used by the package management system
    apt_key:
      url: https://www.mongodb.org/static/pgp/server-4.4.asc
      state: present

  - name: Add MongoDB repository
    apt_repository:
      repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/{{ mongodb_version }} multiverse"
      state: present

  - name: Install MongoDB server
    apt:
      name: mongodb-org
      state: present
      update_cache: yes

  - name: Ensure MongoDB data directory exists
    file:
      path: "{{ mongodb_data_dir }}"
      state: directory
      owner: mongodb
      group: mongodb
      mode: 0700

  - name: Update MongoDB configuration file to use separate partition
    replace:
      path: /etc/mongod.conf
      regexp: 'dbPath: /var/lib/mongodb'
      replace: "dbPath: {{ mongodb_data_dir }}"

  - name: Restart MongoDB server
    systemd:
      name: mongod
      state: restarted
      enabled: true
    notify: Start MongoDB service

  handlers:
  - name: Start MongoDB service
    systemd:
      name: mongod
      state: started
      enabled: true

