# tasks file for nfs_server_setup
- hosts: nfs_storage
  become: yes
- name: Include variables
  include_vars: group_vars.yml
  tasks:
  - name: Install NFS server package
    apt:
      name: nfs-kernel-server
      state: present
      update_cache: yes

  - name: Ensure NFS exports directory exists
    file:
      path: "{{ nfs_export_directory }}"
      state: directory
      owner: nobody
      group: nogroup
      mode: 0777

  - name: Add NFS export
    ansible.builtin.lineinfile:
      path: /etc/exports
      line: "{{ nfs_export_directory }} *(rw,sync,no_subtree_check,no_root_squash)"
      state: present
    notify: Export NFS shares

  - name: Restart and enable NFS server
    ansible.builtin.service:
      name: nfs-kernel-server
      state: restarted
      enabled: true
    ignore_errors: yes


